from hamcrest.core.base_matcher import BaseMatcher
from hamcrest.core.string_description import StringDescription


class MetaMatcher(BaseMatcher):
    """A class that checks matchers.

    When new matchers are developed, it is vital to check that they match
    as expected and produce helpful desriptions and mismatch_descriptions.

    This metamatcher does exactly that.

    Say, you have written a matcher called ``is_twice_as_big_as``, and you want it
    to compare ints. You intend to use it like this::

        assert_that(4, is_twice_as_big_as(2))

    Under the hood, the following is called::

        is_twice_as_big_as(2)._matches(4)

    Keeping that in mind, here's how you can check your matcher with the
    metamatcher::

        def test_is_twice_as_big_as(...)
            assert_that(
                # Your initialized matcher
                is_twice_as_big_as(2),
                # The metamatcher specifying the value for matching
                matches(4)
            )

    This will fail if your ``is_twice_as_big_as`` matcher doesn't match.

    To check that your matcher produces the correct description::

        def test_is_twice_as_big_as(...)
            assert_that(
                is_twice_as_big_as(2),
                matches(4).with_description("An int twice as big as <2>")
            )

    This will fail if your ``is_twice_as_big_as`` matcher doesn't match,
    if the description it produces is wrong, or both.

    You can also check that your matcher doesn't match in certain situations.
    To do that, use the ``doesnt_match`` function, and to check the mismatch
    description, call the ``with_mismatch_description`` method.

    Note, that you can use the ``with_description`` method with the
    ``doesnt_match`` metamatcher, but calling ``with_mismatch_description``
    with the ``matches`` flavour of the metamatcher, will throw an exception.

    """
    def __init__(self, item, result=True):
        self.result = result
        self.item = item
        self.match_result = None

        self.description = None
        self.wrong_description = None

        self.mismatch_description = None
        self.wrong_mismatch_description = None


    def with_description(self, description):
        """Adds the check for the description generated by the matcher that
        is being tested. If this method is not called, the matcher will not
        check the description at all.

        If this method _is_ called, then the description, generated by the
        matcher under test, will be checked. If the actual description doesn't
        match the one set here, the metamatcher will not match.
        """
        self.description = description
        return self


    def with_mismatch_description(self, mismatch_description):
        """Adds the check for the mismatch description generated by the
        matcher being tested. The logic is the same as with
        ::py:meth:`pyhamcrest_metamatchers.metamatchers.MetaMatcher.with_description`
        """
        self.mismatch_description = mismatch_description
        return self


    def _matches(self, matcher):
        ret = True
        self.match_result = matcher._matches(self.item)
        if self.result:
            ret &= self.match_result
        else:
            ret &= not self.match_result

        if self.description:
            descr = StringDescription()
            matcher.describe_to(descr)
            descr = str(descr)
            descr_is_correct = descr == self.description
            if not descr_is_correct:
                self.wrong_description = descr
                ret = False

        if self.mismatch_description:
            descr = StringDescription()
            matcher.describe_mismatch(self.item, descr)
            descr = str(descr)
            descr_is_correct = descr == self.mismatch_description
            if not descr_is_correct:
                self.wrong_mismatch_description = descr
                ret = False

        return ret


    def describe_to(self, description):
        description.append_text("A matcher that ")
        if not self.result:
            description.append_text("does not match ")
        else:
            description.append_text("matches ")
        description.append_text("the item.")

        if self.description:
            description.append_text(" With the description: <{}>".format(
                self.description
            ))

        if self.mismatch_description and self._mismatch_description_should_be_present():
            description.append_text(" With mismatch_description: <{}>".format(
                self.mismatch_description
            ))


    def _mismatch_description_should_be_present(self):
        return self.result == self.match_result == False


    def describe_mismatch(self, item, mismatch_description):
        if self.match_result != self.result:
            mismatch_description.append_text("The matcher ")
            if self.match_result:
                mismatch_description.append_text("matched. ")
            else:
                mismatch_description.append_text("did not match. ")
        if self.wrong_description:
            mismatch_description.append_text("The description was <{}>. ".format(
                self.wrong_description
            ))

        if (
                self.wrong_mismatch_description
                and self._mismatch_description_should_be_present()
        ):
            mismatch_description.append_text("The mismatch_description was <{}>. ".format(
                self.wrong_mismatch_description
            ))


def matches(a_matcher):
    """Checks that the matcher under test matches the value

    :param a_matcher: The matcher that needs to be checked.
    :return: :py:class:`pyhamcrest_metamatchers.metamatchers.MetaMatcher<MetaMatcher>`
    """
    return MetaMatcher(a_matcher)


def doesnt_match(a_matcher):
    """Checks that the matcher under test doesn't match the value

    :param a_matcher: The matcher that needs to be checked.
    :return: :py:class:`pyhamcrest_metamatchers.metamatchers.MetaMatcher<MetaMatcher>`
    """
    return MetaMatcher(a_matcher, False)
